/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ConstructorDemo1 */

#ifndef _Included_ConstructorDemo1
#define _Included_ConstructorDemo1
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
