/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class InnerClassDemo */

#ifndef _Included_InnerClassDemo
#define _Included_InnerClassDemo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
